// SPDX-FileCopyrightText: RUST-TOOLCHAIN contributors
//
// SPDX-License-Identifier: MIT OR Apache-2.0

import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Placeholder sidebar for Task 3.
 *
 * This autogenerates a flat sidebar from `content/` purely so the docs
 * plugin has a valid `sidebarPath` to build against. Task 6 replaces this
 * with the hand-authored category structure the migration design calls
 * for — do not build on top of this file.
 */
const sidebars: SidebarsConfig = {
  defaultSidebar: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
