module.exports = {
  extends: ["@commitlint/config-conventional"],
  rules: {
    "type-enum": [
      2,
      "always",
      [
        "init",
        "build",
        "ci",
        "chore",
        "docs",
        "feat",
        "fix",
        "perf",
        "refactor",
        "revert",
        "style",
        "test",
      ],
    ],
    "scope-enum": [
      1,
      "always",
      [
        "api",
        "aws",
        "cli",
        "config",
        "deps",
        "docker",
        "docs",
        "metrics",
        "moderation",
        "resilience",
        "services",
        "sqs",
        "tests",
      ],
    ],
    "scope-empty": [1, "never"],
    "subject-case": [0, "never"],
    "subject-empty": [2, "never"],
    "subject-full-stop": [2, "never", "."],
    "header-max-length": [2, "always", 100],
    "body-max-line-length": [1, "always", 100],
  },
};
