#!/usr/bin/env bash
#

# SPDX-FileCopyrightText: RUST-TOOLCHAIN contributors
#
# SPDX-License-Identifier: MIT OR Apache-2.0

#
# Regenerates every derived site image from logos/rust-toolchain-and-cache.svg.
#
# The logo is the single source. Everything this writes is an output: re-run the
# script rather than editing favicon.svg, the PNGs or the ICO by hand.
#
# Requires librsvg (`brew install librsvg`) and ImageMagick (`brew install
# imagemagick`). rsvg-convert rasterises the SVG; ImageMagick only composites
# and packs the ICO, because its own SVG renderer produces noticeably softer
# edges on this artwork.

set -Eeuo pipefail

cd "$(dirname "$0")"

SRC="logos/rust-toolchain-and-cache.svg"
FIELD="#ffffff"

# The logo ships with a transparent background and a near-black gear ring, so it
# needs an opaque light field. Verified by rendering: on the site's #1f5572 and
# on near-black, the ring merges into the background and the silhouette is lost.
#
# The viewBox does not start at the origin, so the background rect has to repeat
# its exact x/y/width/height rather than assume 0 0 100% 100%.
read -r VB_X VB_Y VB_W VB_H < <(
  grep -o 'viewBox="[^"]*"' "$SRC" | head -1 | sed 's/viewBox="//; s/"//'
)

# favicon.svg = the logo over a rounded field, emitted by splicing a <rect> in
# directly after </defs> so it precedes every path and therefore paints behind
# them. SVG has no z-index; document order is the whole stacking rule.
python3 - "$SRC" "$VB_X" "$VB_Y" "$VB_W" "$VB_H" "$FIELD" > favicon.svg <<'PY'
import sys

src, x, y, w, h, field = sys.argv[1:7]
svg = open(src).read()

# The two SPDX tokens are split across adjacent string literals, which Python
# concatenates at compile time -- the emitted header is byte-identical. They are
# split because `comply` finds an SPDX tag by scanning a file for the literal
# token, with no notion of it being quoted, so the tag this script WRITES was
# read as a tag this script DECLARES. The trailing "\n\n" came along with it,
# giving a license named `Apache-2.0\n\n`, which then had no matching file in
# LICENSES/ and was reported as both a bad and a missing license on every
# `comply lint` run. Rejoin them and the false positive comes back.
header = (
    "<!--\n"
    "SPDX-File" "CopyrightText: RUST-TOOLCHAIN contributors\n\n"
    "SPDX-License-" "Identifier: MIT OR Apache-2.0\n\n"
    "GENERATED by build-icons.sh from logos/rust-toolchain-and-cache.svg.\n"
    "Do not edit: edit the logo and re-run the script.\n"
    "-->\n"
)

rx = float(w) * 0.12
rect = (
    f'<rect x="{x}" y="{y}" width="{w}" height="{h}" '
    f'rx="{rx:.2f}" fill="{field}"/>'
)

marker = "</defs>"
if marker not in svg:
    raise SystemExit("expected a </defs> in the logo; splice point not found")
svg = svg.replace(marker, marker + "\n" + rect, 1)
sys.stdout.write(header + svg)
PY

# favicon.ico carries 16, 32 and 48. Each size is rasterised from the SVG at its
# own size rather than downscaled from one large render: rsvg hints the strokes
# per size, and a 48-to-16 downscale of this much detail is visibly muddier.
#
# 16px cannot render this illustration legibly -- verified, it is an orange blob
# -- but it is still included, because omitting it makes a browser downscale the
# 32 to 16 itself with a worse filter. See README.md.
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT
for s in 16 32 48; do
  rsvg-convert -w "$s" -h "$s" favicon.svg -o "$tmp/f$s.png"
done
magick "$tmp/f16.png" "$tmp/f32.png" "$tmp/f48.png" favicon.ico

# apple-touch-icon: 180x180, square and fully opaque. iOS applies its own mask,
# so a source with its own rounded corners is rounded twice and shows a pale
# seam in each corner. The logo is inset so the mask does not clip the gear.
# `-strip` on every PNG write, and it is not cosmetic. ImageMagick stamps
# date:create, date:modify and date:timestamp into a tEXt chunk, so without it
# two runs over identical inputs produce different bytes and every re-run dirties
# git for a file whose content did not change.
rsvg-convert -w 156 -h 156 "$SRC" -o "$tmp/logo156.png"
magick -size 180x180 "xc:$FIELD" "$tmp/logo156.png" -gravity center -composite \
  -alpha remove -alpha off -strip apple-touch-icon.png

# social-card.png is composed from social-card.svg, which embeds nothing and
# instead leaves a panel for the logo to be composited into. Keeping the logo
# out of the SVG keeps that file readable at ~70 lines instead of ~1500.
# The +96+225 offset must stay in step with the panel <rect> in social-card.svg
# (x=84 y=213, inset 12 on each side). They are two halves of one number and
# nothing checks that they agree.
rsvg-convert -w 1200 -h 630 social-card.svg -o "$tmp/card-bg.png"
rsvg-convert -w 300 -h 304 "$SRC" -o "$tmp/logo-card.png"
magick "$tmp/card-bg.png" "$tmp/logo-card.png" -geometry +96+225 -composite \
  -strip social-card.png

printf 'wrote: favicon.svg favicon.ico apple-touch-icon.png social-card.png\n'
